# Generated by Django 3.1.7 on 2021-03-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='antenna',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
