# Generated by Django 3.1.7 on 2021-04-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20210411_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_name', models.CharField(max_length=20)),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
        ),
    ]
