# Generated by Django 3.1.7 on 2021-04-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210331_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='taken_at',
            new_name='registered_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='current_user',
            new_name='recent_user',
        ),
        migrations.AddField(
            model_name='entry',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='antenna',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
