# Generated by Django 3.1.7 on 2021-04-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_bag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='antenna',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='antenna',
        ),
        migrations.AddField(
            model_name='bag',
            name='antenna',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.antenna'),
        ),
        migrations.AddField(
            model_name='bag',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='bag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tags.bag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='bag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='tags.bag'),
        ),
    ]
