# Generated by Django 3.1.7 on 2021-04-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20210411_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='on_board',
            new_name='onboard',
        ),
        migrations.AlterField(
            model_name='bag',
            name='antenna',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bag', to='tags.antenna'),
        ),
    ]
