# Generated by Django 3.1.7 on 2021-04-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20210402_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='has_left',
            field=models.BooleanField(default=False),
        ),
    ]
