# Generated by Django 3.1.7 on 2021-04-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20210411_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='is_open',
        ),
        migrations.AddField(
            model_name='bag',
            name='is_closed',
            field=models.BooleanField(default=True),
        ),
    ]
