# Generated by Django 3.1.7 on 2021-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20210411_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='tag_id',
            field=models.CharField(max_length=30),
        ),
    ]
