# Generated by Django 3.1.7 on 2021-04-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_tag_has_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='last_time_left',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
