# Generated by Django 3.1.7 on 2021-04-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_auto_20210411_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenna',
            name='name',
            field=models.CharField(default='Ant:0', max_length=10),
            preserve_default=False,
        ),
    ]
