# Generated by Django 3.1.7 on 2021-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_antenna_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='no',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='tag_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='bag_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
