# Generated by Django 3.1.7 on 2021-04-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_auto_20210411_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bag_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
