# Generated by Django 3.1.7 on 2021-04-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_auto_20210411_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='bag_name',
            new_name='name',
        ),
    ]
