# Generated by Django 3.1.7 on 2021-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_auto_20210411_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenna',
            name='is_door',
            field=models.BooleanField(default=False),
        ),
    ]
