# Generated by Django 3.1.7 on 2021-04-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0013_antenna_is_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='current_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.profile'),
        ),
    ]
