# Generated by Django 3.1.7 on 2021-04-19 21:11

from django.db import migrations, models
import tags.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0016_auto_20210412_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='registered_at',
            field=models.DateTimeField(default=tags.models.now),
        ),
    ]
