# Generated by Django 3.1.7 on 2021-04-19 21:27

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0017_auto_20210420_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_key',
            field=models.CharField(default=tags.models.generate_code, max_length=10),
        ),
    ]
